#!/usr/bin/env python
"""Generate vault/wiki/_status.md — a health dashboard browsable inside Obsidian.

It reads the vault through `scrip` (status + verify) and writes a markdown note
with wiki-links to fresh pages and call-outs for anything stale or broken. The
note has no frontmatter / `derived-from`, so it is a *view*, never a tracked
artifact — it cannot itself go stale or affect the dependency graph.

    uv run --project scrip python adapters/obsidian/dashboard.py

Wire it into a cron job or a Claude Code hook to keep the dashboard fresh.
"""

from __future__ import annotations

from pathlib import Path

from scrip import anchors, graph, query

ROOT = Path(__file__).resolve().parents[2]


def main() -> None:
    st = graph.compute_status(ROOT, use_cache=False)
    vf = anchors.verify_vault(ROOT)
    _, contradictions = query.run(ROOT, name="contradictions")

    out: list[str] = [
        "# Vault status",
        "",
        "> Generated by `adapters/obsidian/dashboard.py` — do not edit by hand.",
        "",
        f"- **Artifacts:** {len(st['ok'])} OK · {len(st['stale'])} stale · "
        f"{len(st['uncompiled'])} uncompiled source(s)",
        f"- **Citations:** {vf['ok']}/{vf['checked']} resolve · "
        f"{len(vf['ambiguous'])} ambiguous · {len(vf['broken'])} broken",
        f"- **Contradictions:** {len(contradictions)} open",
        "",
    ]

    if st["stale"]:
        out += ["## ⚠️ Stale — needs recompile", ""]
        for s in st["stale"]:
            changed = (
                f" — changed: {', '.join(s['changed_sources'])}"
                if s.get("changed_sources")
                else ""
            )
            out.append(f"- `{s['id']}` — {s['reason']}{changed}")
        out.append("")

    if vf["broken"]:
        out += ["## ❌ Broken citations", ""]
        for b in vf["broken"]:
            out.append(f"- {b['where']} → `{b['source_id']}`")
        out.append("")

    if contradictions:
        out += ["## ⚠️ Open contradictions", ""]
        for c in contradictions:
            out.append(
                f"- `{c['claim_a']}` vs `{c['claim_b']}` — "
                f"{c['subject']} / {c['predicate']}"
            )
        out.append("")

    out += ["## ✅ Fresh artifacts", ""]
    for o in st["ok"]:
        slug = o["id"].split("/")[-1]
        out.append(f"- [[{slug}]] — `{o['id']}`")
    out.append("")

    if st["uncompiled"]:
        out += ["## 📥 Uncompiled sources", ""]
        for u in st["uncompiled"]:
            out.append(f"- `{u['id']}`")
        out.append("")

    target = ROOT / "vault" / "wiki" / "_status.md"
    target.write_text("\n".join(out), encoding="utf-8")
    print(
        f"wrote {target.relative_to(ROOT)} — "
        f"{len(st['ok'])} OK, {len(st['stale'])} stale, "
        f"{len(vf['broken'])} broken citations, {len(contradictions)} contradictions"
    )


if __name__ == "__main__":
    main()
