#!/usr/bin/env python
"""Generate vault/wiki/_graph.md — a browsable view of the relationship graph.

The typed edges in ``facts/graph.ndjson`` (``builds-on``, ``cites``, ``about``,
``made-by`` …) are the most connected structure in a vault, yet they live in
NDJSON and are invisible to Obsidian's native graph view — which only follows
``[[wiki-links]]`` and footnote targets. This script renders those edges as a
single clickable note: per node, its outbound and inbound typed links.

It is a *view*, exactly like ``dashboard.py``: the note has no frontmatter, so it
is never a tracked artifact, can never go stale, and never affects the dependency
graph. ``facts/graph.ndjson`` stays the source of truth; delete this note (or the
whole adapter) and the vault is still fully valid.

A note on Obsidian's graph *view*: because every link lives in this one file, the
graph view shows ``_graph`` as a single hub, not true page-to-page edges — that
would require editing the tracked pages, which would make their ``input-hash``
lie. For an interactive relationship graph, query the edges with
``scrip query edges`` or render them with the Dataview plugin. This note's value
is one clickable map of the relationship layer.

    uv run --project scrip python adapters/obsidian/graph_view.py

Wire it into a cron job or a Claude Code hook to keep the view fresh.
"""

from __future__ import annotations

from pathlib import Path

from scrip import facts_dir, query

ROOT = Path(__file__).resolve().parents[2]


def _slug(node_id: str) -> str:
    """Obsidian resolves ``[[name]]`` by basename — same mapping as dashboard.py."""
    return node_id.split("/")[-1]


def main() -> None:
    graph_file = facts_dir(ROOT) / "graph.ndjson"
    rows: list[dict] = []
    if graph_file.exists():
        # Read through the same query lens as `scrip query edges`, not by
        # re-parsing the NDJSON, so this view can never drift from the CLI.
        _, rows = query.run(ROOT, name="edges")

    # node id -> rendered edge lines, kept separate so each node section lists
    # what it points at, then what points at it.
    out_edges: dict[str, list[str]] = {}
    in_edges: dict[str, list[str]] = {}
    for e in rows:
        src, dst, kind = e["src"], e["dst"], e["kind"]
        out_edges.setdefault(src, []).append(f"- {kind} → [[{_slug(dst)}]] (`{dst}`)")
        in_edges.setdefault(dst, []).append(f"- {kind} ← [[{_slug(src)}]] (`{src}`)")

    nodes = sorted(set(out_edges) | set(in_edges))

    lines: list[str] = [
        "# Vault graph",
        "",
        "> Generated by `adapters/obsidian/graph_view.py` — do not edit by hand.",
        "> A clickable view of `facts/graph.ndjson` (the source of truth).",
        "",
        f"- **Edges:** {len(rows)} across {len(nodes)} node(s)",
        "",
    ]

    if not nodes:
        lines += ["_No edges in `facts/graph.ndjson` yet._", ""]

    for node in nodes:
        lines.append(f"## `{node}`")
        lines += sorted(out_edges.get(node, []))
        lines += sorted(in_edges.get(node, []))
        lines.append("")

    target = ROOT / "vault" / "wiki" / "_graph.md"
    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)} — {len(rows)} edge(s), {len(nodes)} node(s)")


if __name__ == "__main__":
    main()
